apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubernetes.io/change-cause: kubectl deployment.apps/safedesk-web set image deployment.v1.apps/safedesk-web
      safedesk-web=latest --record=true
  creationTimestamp: "2020-12-22T20:02:37Z"
  generation: 6
  labels:
    app: safedesk-web
  name: safedesk-web
  namespace: default
  resourceVersion: "31860050"
  selfLink: /apis/apps/v1/namespaces/default/deployments/safedesk-web
  uid: 11aa9ca6-a295-48bf-ae2d-cd211098eb38
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: safedesk-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: safedesk-web
    spec:
      containers:
      - image: gcr.io/savvy-scion-244419/safedesk-web:latest
        imagePullPolicy: Always
        name: safedesk-web-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-12-22T20:02:40Z"
    lastUpdateTime: "2020-12-22T20:02:40Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-12-22T20:02:37Z"
    lastUpdateTime: "2020-12-22T20:02:40Z"
    message: ReplicaSet "safedesk-web-64c9467698" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 6
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1